[test]
root = "src"  # Only scan for tests in the src directory
coverageIgnoreSourcemaps = true  # Don't use sourcemaps for coverage analysis
coverageReporter = ["text", "lcov"]
coverageSkipTestFiles = true  # Exclude test files from coverage reports
coverageThreshold = { functions = 1.0, statements = 1.0, lines = 0.75 }
